// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"
import { Document } from "@contentful/rich-text-types"

export interface IArrayFields {
  /** Title */
  title?: string | undefined

  /** Items */
  items?: Entry<{ [fieldId: string]: unknown }>[] | undefined
}

export interface IArray extends Entry<IArrayFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "array"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IProjectFields {
  /** Title */
  title?: string | undefined

  /** Slug */
  slug?: string | undefined

  /** Thumbnail */
  thumbnail?: Asset | undefined

  /** Introduction */
  introduction?: string | undefined

  /** Body */
  body?: string | undefined

  /** Images */
  images?: Asset[] | undefined

  /** Tags */
  tags?:
    | (
        | "product design"
        | "graphic design"
        | "web design"
        | "writing"
        | "branding"
      )[]
    | undefined
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "project"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface ITextFields {
  /** Title */
  title?: string | undefined

  /** Text */
  text?: string | undefined
}

export interface IText extends Entry<ITextFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "text"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export type CONTENT_TYPE = "array" | "project" | "text"

export type LOCALE_CODE = "en-US"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US"
